name: chargewise_my
description: EV Infrastructure Decision Support System planning module.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  supabase_flutter: ^2.10.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.0
  provider: ^6.1.5
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.10.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icons/
    - assets/images/
